function [obs] = r_rnxobsv2(f_obs,inf,options,dcb)
%% Read RINEX Version 2.x Observation Data Body
% Function:
%     This function reads the data body of a RINEX version 2.x observation
%     (OBS) file. It is highly dependent on the header information structure
%     `inf` (generated by `r_rnxheadv2`), especially using `inf.seq` to
%     correctly map and extract dual-frequency observations.
%
%     !!! CRITICAL WARNING !!!
%     This function includes a strict data validation check. If the total
%     number of parsed epochs exceeds 2881 (the maximum expected for a
%     standard 24-hour day with a 30-second interval), the function will
%     assume the file is corrupt or anomalous, **DELETE THE INPUT FILE**,
%     and return an empty matrix. Use with extreme caution!
%
%     The function is designed to parse the unique RINEX v2 satellite list
%     format, which may span multiple lines. It filters systems and applies
%     DCB corrections based on the `options` structure. Carrier phase data is
%     converted from cycles to meters.
%
% INPUT:
%     f_obs:    Path to the RINEX v2 observation file.
%               (Note: This file will be deleted if it fails the validation check).
%     inf:      Header information structure, returned by `r_rnxheadv2`.
%     options:  A structure with processing options.
%               - options.system: Specifies systems to process (e.g., .gps=1).
%               - options.dcb:    Flag to apply DCB correction (1 for yes, 0 for no).
%     dcb:      (Optional) An array of Differential Code Bias (DCB) values.
%               Required if `options.dcb` is set to 1.
%
% OUTPUT:
%     obs:      A structure containing all extracted and processed observation data.
%               - obs.p1: P1/C1 pseudorange matrix (meters).
%               - obs.p2: P2/C2 pseudorange matrix (meters).
%               - obs.l1: L1 carrier phase matrix (meters).
%               - obs.l2: L2 carrier phase matrix (meters).
%               - obs.ep: Vector of epoch times (seconds of day).
%               - obs.st: Status matrix (1 if data exists, 0 otherwise).
%               Returns an empty matrix `[]` if the file is rejected and deleted.
%% ---------------------------------------------------------------------

[fid,errmsg] = fopen(f_obs);

if any(errmsg)
    errordlg('RINEX file can not be opened !','RINEX file error');
    error   ('RINEX file error');
end

sno = 105;

if inf.time.last == 86400
    fi = inf.time.first(4,1)*3600 + inf.time.first(5,1)*60 + inf.time.first(6,1);
    la = inf.time.last;
    max = (la-fi)/inf.time.int + 1;
else
    fi = inf.time.first(4,1)*3600 + inf.time.first(5,1)*60 + inf.time.first(6,1);
    la = inf.time.last (4,1)*3600 + inf.time.last (5,1)*60 + inf.time.last (6,1);
    max = (la-fi)/inf.time.int + 1;
end

p1s  =   NaN(max,sno);
p2s  =   NaN(max,sno);
l1s  =   NaN(max,sno);
l2s  =   NaN(max,sno);
eps  =   NaN(max, 1);
sts  =  zeros(max,sno);
[~,wavl] = frequencies;


d.year = inf.time.first(1);
d.mon  = inf.time.first(2);
d.day  = inf.time.first(3);
if d.year<2000
    d.year = d.year - 1900;
else
    d.year = d.year - 2000;
end


epno  = 0;
linenum = 0;
while ~feof(fid)
    
    tline = fgetl(fid);
    linenum = linenum + 1;
    
    if size(tline,2)<32
        ep    = sscanf(tline(1:end),'%f',[1,8]);
    else
        ep    = sscanf(tline(1:32),'%f',[1,8]);
    end
    
    if length(ep)==8 && ep(1)==d.year && ep(2)==d.mon && ep(3)==d.day && size(tline,2)>33
        epno  = epno + 1;
        epocs = ep(4)*3600 + ep(5)*60 + ep(6);
        eps(epno,1) = epocs;
        sats_no = ep(8);
        
        if sats_no<13
            if length(tline)<68
                satline = strtrim(tline(33:end));
            elseif length(tline)<=80
                satline = strtrim(tline(33:68));
            end
        elseif sats_no<25
            if length(tline)<68
                satline1 = strtrim(tline(33:end));
            elseif length(tline)<=80
                satline1 = strtrim(tline(33:68));
            end
            tline = fgetl(fid);
            linenum = linenum + 1;
            if length(tline)<68
                satline2 = strtrim(tline(33:end));
            elseif length(tline)<=80
                satline2 = strtrim(tline(33:68));
            end
            satline = strcat(satline1,satline2);
        elseif sats_no<37
            if length(tline)<68
                satline1 = strtrim(tline(33:end));
            elseif length(tline)<=80
                satline1 = strtrim(tline(33:68));
            end
            tline = fgetl(fid);
            linenum = linenum + 1;
            if length(tline)<68
                satline2 = strtrim(tline(33:end));
            elseif length(tline)<=80
                satline2 = strtrim(tline(33:68));
            end
            tline = fgetl(fid);
            linenum = linenum + 1;
            if length(tline)<68
                satline3 = strtrim(tline(33:end));
            elseif length(tline)<=80
                satline3 = strtrim(tline(33:68));
            end
            satline = strcat(satline1,satline2,satline3);
        end
        
        if any(strfind(satline,'G')) || any(strfind(satline,'R')) || any(strfind(satline,'E'))
            satline=strrep(satline,'G','1');
            satline=strrep(satline,' ','0');
            satline=strrep(satline,'R','2');
            satline=strrep(satline,'E','3');
            satline=strrep(satline,'S','4');
            satline=strrep(satline,'T','4');
        end
        
        sat = sscanf(satline,'%3d');
        
        if options.system.gps == 1
            dtc = find(sat>100 & sat<133);
            sat(dtc) = sat(dtc) - 100;
        end
        
        if options.system.glo == 1
            dtc = find(sat>200 & sat<227);
            sat(dtc) = sat(dtc) - 200 + 32;
        end
        
        if options.system.gal == 1
            dtc = find(sat>310 & sat<331);
            sat(dtc) = sat(dtc) - 300 + 48;
        end
        
        for i=sat'
            
            ls = NaN(1,inf.obsno);
            if i>100
                for k=1:ceil(inf.obsno/5)
                    fgetl(fid);
                    linenum = linenum + 1;
                end
            else
                for k=1:ceil(inf.obsno/5)
                    tline = fgetl(fid);
                    linenum = linenum + 1;
                    for n=0:4
                        st = (16*n+1); fn = (16*(n+1)-2);
                        if fn<=length(tline)
                            tls= sscanf(tline(st:fn),'%f');
                            if ~isempty(tls)
                                ls((5*(k-1))+(n+1)) = tls;
                            end
                        end
                    end
                end
                if i<33
                    % P1
                    if (inf.seq.gps(1)==0) || (isnan(ls(inf.seq.gps(1))))
                        if options.dcb == 1
                            p1s(epno,i) = ls(inf.seq.gps(5)) + dcb(i,1);
                        else
                            p1s(epno,i) = ls(inf.seq.gps(5));
                        end
                    else
                        p1s(epno,i) = ls(inf.seq.gps(1));
                    end
                    % P2
                    p2s(epno,i) = ls(inf.seq.gps(2));
                    % L1
                    l1s(epno,i) = ls(inf.seq.gps(3))*wavl(i,1);
                    % L2
                    l2s(epno,i) = ls(inf.seq.gps(4))*wavl(i,2);
                elseif i<59
                    % P1
                    if (inf.seq.glo(1)==0) || (isnan(ls(inf.seq.glo(1))))
                        if options.dcb == 1
                            p1s(epno,i) = ls(inf.seq.glo(5)) + dcb(i,1);
                        else
                            p1s(epno,i) = ls(inf.seq.glo(5));
                        end
                    else
                        p1s(epno,i) = ls(inf.seq.glo(1));
                    end
                    p2s(epno,i) = ls(inf.seq.glo(2));
                    l1s(epno,i) = ls(inf.seq.glo(3))*wavl(i,1);
                    l2s(epno,i) = ls(inf.seq.glo(4))*wavl(i,2);
                elseif i<89 && all(inf.seq.gal> 0)
                    p1s(epno,i) = ls(inf.seq.gal(1));
                    p2s(epno,i) = ls(inf.seq.gal(2));
                    l1s(epno,i) = ls(inf.seq.gal(3))*wavl(i,1);
                    l2s(epno,i) = ls(inf.seq.gal(4))*wavl(i,2);
                end
            end
        end
    end
end

alldata = p1s + p2s + l1s + l2s;
if size(alldata,1)<=2881
sts(~isnan(alldata)) = 1;
if max>epno
    p1s(epno+1:max,:) = [];
    p2s(epno+1:max,:) = [];
    l1s(epno+1:max,:) = [];
    l2s(epno+1:max,:) = [];
    eps(epno+1:max,:) = [];
    sts(epno+1:max,:) = [];
end

obs.p1 = p1s;
obs.p2 = p2s;
obs.l1 = l1s;
obs.l2 = l2s;
obs.ep = eps;
obs.st = sts;
fclose('all');
else
    fclose('all');
    delete(f_obs);
    obs=[];
end
end