from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path


CATEGORY_TO_SUBDIR = {
    "input_obs": "raw/obs",
    "input_sp3": "raw/sp3",
    "input_clk": "raw/clk",
    "input_atx": "raw/atx",
    "golden_roti": "golden/roti",
    "golden_aatr": "golden/aatr",
    "golden_rmsaatr": "golden/rmsaatr",
    "golden_crot": "golden/crot",
    "golden_dixsg": "golden/dixsg",
    "golden_sigmaphi": "golden/sigmaphi",
}


README_TEMPLATE = """# MATLAB Sample Mapping

This directory is generated by `scripts/sync_matlab_samples.py`.
It mirrors MATLAB sample input and golden outputs for dataset `{dataset_id}` (DOY {doy}, date {date}).

Rules:
- Do not edit files in this directory manually.
- Re-run the sync script if source data changes.
- Validation and regression should use this mapped dataset as one baseline source.
"""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def ensure_readme(target_root: Path, *, dataset_id: str, doy: str, date: str) -> None:
    readme_path = target_root / "README.md"
    content = README_TEMPLATE.format(
        dataset_id=dataset_id or "unknown",
        doy=doy or "unknown",
        date=date or "unknown",
    )
    readme_path.write_text(content, encoding="utf-8")


def sync_entry(src: Path, dst: Path, expected_sha: str, mode: str) -> str:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() and sha256_file(dst) == expected_sha:
        return "skipped"

    if dst.exists():
        dst.unlink()

    if mode == "hardlink":
        try:
            dst.hardlink_to(src)
            return "linked"
        except OSError:
            shutil.copy2(src, dst)
            return "copied"

    shutil.copy2(src, dst)
    return "copied"


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync MATLAB sample dataset into workspace samples.")
    parser.add_argument(
        "--manifest",
        default="config/datasets/matlab_24084_manifest.json",
        help="Manifest path relative to project root.",
    )
    parser.add_argument(
        "--target",
        default="workspace/samples/matlab_24084",
        help="Target root path relative to project root.",
    )
    parser.add_argument(
        "--mode",
        choices=["copy", "hardlink"],
        default="copy",
        help="Sync mode: copy or hardlink (fallback to copy).",
    )
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    manifest_path = (project_root / args.manifest).resolve()
    target_root = (project_root / args.target).resolve()
    target_root.mkdir(parents=True, exist_ok=True)
    for rel in sorted(set(CATEGORY_TO_SUBDIR.values()) | {"raw/nav"}):
        (target_root / rel).mkdir(parents=True, exist_ok=True)

    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    ensure_readme(
        target_root,
        dataset_id=str(manifest.get("datasetId") or ""),
        doy=str(manifest.get("doy") or ""),
        date=str(manifest.get("date") or ""),
    )
    report = {
        "datasetId": manifest.get("datasetId"),
        "timestampUtc": datetime.now(timezone.utc).isoformat(),
        "mode": args.mode,
        "copied": 0,
        "linked": 0,
        "skipped": 0,
        "missing": [],
    }

    for entry in manifest.get("entries", []):
        category = entry.get("category")
        rel_dir = CATEGORY_TO_SUBDIR.get(category)
        if not rel_dir:
            continue

        src = Path(entry["path"])
        dst = target_root / rel_dir / src.name
        if not src.exists():
            report["missing"].append(str(src))
            continue

        status = sync_entry(src, dst, entry["sha256"], args.mode)
        report[status] += 1

    report_path = target_root / "sync_report.json"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Sync finished: {report_path}")
    print(f"copied={report['copied']} linked={report['linked']} skipped={report['skipped']}")
    if report["missing"]:
        print(f"missing={len(report['missing'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
