# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

block_cipher = None

SRC = Path(SPECPATH) / "src"
ISD = SRC / "isd"
CONFIG = Path(SPECPATH) / "config"

a = Analysis(
    ["src/isd/__main__.py"],
    pathex=["src"],
    binaries=[],
    datas=[
        # DB migrations
        (str(ISD / "infrastructure" / "db" / "migrations"), "isd/infrastructure/db/migrations"),
        # Default config JSON files
        (str(CONFIG / "defaults"), "config/defaults"),
    ],
    hiddenimports=[
        "isd",
        "isd.__main__",
        "isd.__init__",
        "isd.settings",
        "isd.runtime",
        "isd.runtime.crash",
        "isd.algorithms",
        "isd.algorithms.metrics",
        "isd.algorithms.preprocess",
        "isd.algorithms.rinex_compute",
        "isd.algorithms.sp3_orbit",
        "isd.algorithms.matlab_metrics",
        "isd.application",
        "isd.application.bootstrap",
        "isd.application.channels",
        "isd.application.command_bus",
        "isd.application.ids",
        "isd.application.project_service",
        "isd.application.report_service",
        "isd.application.result_service",
        "isd.application.risk_flags",
        "isd.application.settings_service",
        "isd.application.task_service",
        "isd.application.template_service",
        "isd.domain",
        "isd.domain.enums",
        "isd.domain.models",
        "isd.domain.state_machine",
        "isd.infrastructure",
        "isd.infrastructure.db",
        "isd.infrastructure.db.sqlite",
        "isd.infrastructure.filesystem",
        "isd.infrastructure.filesystem.file_scan",
        "isd.infrastructure.filesystem.paths",
        "isd.infrastructure.filesystem.product_match",
        "isd.infrastructure.filesystem.result_store",
        "isd.infrastructure.filesystem.rinex_parser",
        "isd.infrastructure.filesystem.rinex_reader",
        "isd.infrastructure.logging",
        "isd.infrastructure.logging.logger",
        "isd.infrastructure.repositories",
        "isd.infrastructure.repositories.base",
        "isd.infrastructure.repositories.project_file_repository",
        "isd.infrastructure.repositories.project_repository",
        "isd.infrastructure.repositories.result_repository",
        "isd.infrastructure.repositories.settings_repository",
        "isd.infrastructure.repositories.station_repository",
        "isd.infrastructure.repositories.task_log_repository",
        "isd.infrastructure.repositories.task_repository",
        "isd.infrastructure.repositories.task_step_repository",
        "isd.infrastructure.repositories.template_repository",
        "isd.infrastructure.repositories.validation_repository",
        "isd.providers",
        "isd.providers.interfaces",
        "isd.providers.stub_providers",
        "isd.ui",
        "isd.ui.main_window",
        "isd.ui.pages",
        "isd.ui.pages.home_page",
        "isd.ui.pages.analysis_page",
        "isd.ui.pages.project_page",
        "isd.ui.pages.report_page",
        "isd.ui.pages.settings_page",
        "isd.ui.pages.task_page",
        "isd.ui.pages.visualization_page",
        "isd.ui.widgets",
        "isd.ui.widgets.side_nav",
        "isd.ui.widgets.top_bar",
        "isd.workers",
        "isd.workers.task_worker",
        # PySide6 / PyQt hidden imports
        "PySide6.QtWidgets",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtSql",
        "pyqtgraph",
        "pydantic",
        "pydantic_settings",
        "numpy",
        "scipy",
        "pandas",
        "pyarrow",
        "structlog",
        "dateutil",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "IPython",
        "notebook",
        "jupyterlab",
    ],
    noarchive=False,
    optimize=0,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="电离层闪烁监测软件",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="电离层闪烁监测软件",
)
